import {
  pgTable,
  text,
  uuid,
  timestamp,
  boolean,
  integer,
  real,
  jsonb,
  uniqueIndex,
  index,
  primaryKey,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

/* ------------------------------------------------------------------ *
 * Auth tables (user/session/account/verification) are generated by the
 * Better Auth CLI into ./auth-schema.ts and re-exported at the bottom.
 * App tables reference `user.id` (text) via plain text columns rather
 * than hard FKs, to avoid coupling migration order to the auth schema.
 * ------------------------------------------------------------------ */

// --- Domain string unions (kept as text for flexibility) -------------

export const LEAD_STATUSES = [
  "new",
  "in_progress",
  "contacted",
  "callback",
  "booked",
  "not_interested",
  "do_not_call",
  "bad_number",
  "closed",
] as const;
export type LeadStatus = (typeof LEAD_STATUSES)[number];

export const CALL_OUTCOMES = [
  "connected",
  "voicemail",
  "no_answer",
  "busy",
  "gatekeeper",
  "wrong_number",
  "not_interested",
  "booked",
  "callback",
  "do_not_call",
  "mailbox_full",
  "bad_connection",
] as const;
export type CallOutcome = (typeof CALL_OUTCOMES)[number];

// --- Lead enrichment (provenance + verification, per field) ----------
// Harvested/scraped data is captured WITH its source(s) and a verified
// flag. "verified" = corroborated by >=2 independent sources OR from an
// authoritative source. A single weak source stays unverified and the UI
// renders it as "Unknown / unverified" — never asserted as fact.

export type FieldSource = {
  name: string; // "yelp" | "website" | "nc_rec" | "osm" | "manual"
  url: string | null;
  value: string;
  at: string; // ISO timestamp
};
// Structured weekly hours (officeHours field only), for computing open-now.
// day: 0=Sunday..6=Saturday; open/close: "HHMM" 24h local to the business.
export type DayPeriod = { day: number; open: string; close: string };
export type EnrichedField = {
  value: string;
  verified: boolean;
  confidence: number; // 0..1
  sources: FieldSource[];
  periods?: DayPeriod[];
};
export const ENRICHMENT_FIELDS = [
  "officeHours",
  "dmName",
  "dmTitle",
  "email",
  "website",
  "rating",
  "social",
  "address",
] as const;
export type EnrichmentFieldKey = (typeof ENRICHMENT_FIELDS)[number];
export type LeadEnrichment = Partial<Record<EnrichmentFieldKey, EnrichedField>>;

// Review gating for harvested candidates. Orthogonal to call-progression
// `status`: a lead can be status="new" AND reviewState="pending". null =
// a normal (human-entered / imported) lead, never gated.
export const REVIEW_STATES = ["pending", "approved", "rejected"] as const;
export type ReviewState = (typeof REVIEW_STATES)[number];

// --- Customer reviews (call ammo) ------------------------------------
// Verbatim customer-review snippets captured during harvest (Google Places
// returns up to ~5 "most relevant"). NOT shown raw in the UI — fed to the Key
// Notes AI to surface pain points / hooks. Distinct from `reviewState` above,
// which is harvest gating, not customer reviews.
export type LeadReview = {
  source: string; // "places"
  author: string | null; // reviewer display name
  rating: number | null; // 1..5
  text: string; // review body
  relativeTime: string | null; // "2 months ago"
  publishedAt: string | null; // ISO
};

// --- Leads -----------------------------------------------------------

export const leads = pgTable(
  "leads",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    companyName: text("company_name"),
    contactName: text("contact_name"),
    title: text("title"),
    phone: text("phone"), // original, as imported / for display
    phoneNormalized: text("phone_normalized"), // dedup key
    email: text("email"),
    emails: jsonb("emails").$type<string[]>().default([]),
    website: text("website"),
    status: text("status").$type<LeadStatus>().default("new").notNull(),
    askFor: text("ask_for"), // "gatekeeper said ask for Mike"
    callbackAt: timestamp("callback_at", { withTimezone: true }),
    // Room for extra fields the user discovers later, without a migration.
    customFields: jsonb("custom_fields").$type<Record<string, string>>().default({}),
    // Harvested/scraped data with per-field provenance + verified flag.
    enrichment: jsonb("enrichment").$type<LeadEnrichment>().default({}),
    // AI-generated "must-know before you call" bullets (max ~4), shown on the
    // dial cockpit. Synthesized from enrichment/customFields/notes; never asserts
    // facts that aren't in the source data.
    keyNotes: jsonb("key_notes").$type<string[]>().default([]),
    // Verbatim customer-review snippets (Google Places) — raw ammo for the Key
    // Notes AI to mine pain points/hooks. Not rendered directly in the UI.
    reviews: jsonb("reviews").$type<LeadReview[]>().default([]),
    source: text("source"), // import filename / batch label / "harvest:yelp"
    // Review gating for harvested candidates (null = normal lead).
    reviewState: text("review_state").$type<ReviewState>(),
    assignedTo: text("assigned_to"), // user.id, optional (legacy; see ownerId)
    // --- Multi-rep dialing (shared pool + locking + sticky ownership) ---
    // The rep this lead "belongs" to — set once a rep actually reaches it
    // (connected/voicemail/callback/booked/etc.). Their leads + callbacks route
    // back to them; other reps only see it for an overdue callback (team cover).
    ownerId: text("owner_id"), // user.id
    // Short lease taken when a rep dials, so two reps never call the same number
    // at once. Auto-expires (~10 min) if the rep walks away.
    claimedBy: text("claimed_by"), // user.id holding the lease
    claimedAt: timestamp("claimed_at", { withTimezone: true }),
    // Discarded leads (wrong number, defunct, wrong niche) — excluded from
    // dialing and active lists, but recoverable.
    archived: boolean("archived").default(false).notNull(),
    archivedReason: text("archived_reason"),
    createdBy: text("created_by"), // user.id
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    // The dedup backbone: one lead per normalized phone number.
    uniqueIndex("leads_phone_normalized_uq").on(t.phoneNormalized),
    index("leads_status_idx").on(t.status),
    index("leads_callback_idx").on(t.callbackAt),
  ],
);

// --- Lead activity timeline (notes, calls, status changes) -----------

export const LEAD_EVENT_TYPES = [
  "note",
  "call",
  "voicemail",
  "status_change",
  "booking",
  "import",
  "system",
] as const;
export type LeadEventType = (typeof LEAD_EVENT_TYPES)[number];

export const leadEvents = pgTable(
  "lead_events",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => leads.id, { onDelete: "cascade" }),
    userId: text("user_id"), // author
    type: text("type").$type<LeadEventType>().notNull().default("note"),
    body: text("body"),
    outcome: text("outcome").$type<CallOutcome>(),
    metadata: jsonb("metadata").$type<Record<string, unknown>>().default({}),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("lead_events_lead_idx").on(t.leadId),
    index("lead_events_created_idx").on(t.createdAt),
  ],
);

// --- Scripts (markdown, rendered nicely in the dialer) ---------------

export const scripts = pgTable("scripts", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  contentMarkdown: text("content_markdown").notNull().default(""),
  // Scripts can belong to a campaign (campaign-centric). Plain column (no hard
  // FK) to avoid a circular constraint with campaigns.script_id.
  campaignId: uuid("campaign_id"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// --- Campaigns + membership -----------------------------------------

// Goal of each call in a campaign — shapes the script's "ask" + Auto Notes.
export const CAMPAIGN_GOAL_TYPES = ["meeting", "sale", "qualify", "survey"] as const;
export type CampaignGoalType = (typeof CAMPAIGN_GOAL_TYPES)[number];

// The structured campaign brief (campaigns.briefData). Drives every AI surface
// for the campaign so it works for any vertical, not just property management.
export type CampaignBrief = {
  vertical: string; // "restaurants", "property management", …
  icp: string; // who we're targeting, 1-2 sentences
  geography: string; // "Philadelphia metro"
  extraAreas?: string[]; // suggested surrounding towns to also search
  radiusMiles?: number;
  goal: string; // "book a 15-minute demo"
  goalType?: CampaignGoalType;
  offer: string; // the value proposition pitched on the call
  persona?: string; // decision-maker to ask for ("owner / GM")
  qualifiers?: string[]; // good-fit signals (classifier: approve)
  disqualifiers?: string[]; // skip signals (classifier: reject)
  tone?: string; // voice for the script ("friendly, direct")
  areaCodes?: string[]; // suggested local area codes for the number
  keywords?: string; // primary search term for the scraper
  // Caller study-sheet extras (lib/ai/caller-brief.ts). Captured alongside the
  // generated brief markdown so the structured facts are reusable by other AI.
  painPoints?: string[]; // what the prospect is struggling with
  objections?: { objection: string; response: string }[]; // common pushback + rebuttal
};

export const campaigns = pgTable("campaigns", {
  id: uuid("id").defaultRandom().primaryKey(),
  name: text("name").notNull(),
  description: text("description"), // short one-liner
  brief: text("brief"), // longer markdown brief shown on the overview
  location: text("location"),
  industry: text("industry"),
  // The "active" script shown in the dial session. A campaign can own several
  // scripts (scripts.campaignId); this points at the primary one.
  scriptId: uuid("script_id").references(() => scripts.id, { onDelete: "set null" }),
  // Structured brief that drives ALL of this campaign's AI (lead classifier,
  // Key Notes, Auto Notes, script). Drafted by the campaign builder from a
  // one-line prompt; editable. Genericizes the app off property-management so
  // any vertical (restaurants, etc.) gets correct, campaign-aware AI.
  briefData: jsonb("brief_data").$type<CampaignBrief>(),
  // Booking invite defaults — prefill the Book dialog. Templates support
  // {company} {contact} {first} {city} tokens.
  meetingTitleTemplate: text("meeting_title_template"),
  meetingDescriptionTemplate: text("meeting_description_template"),
  meetingDurationMin: integer("meeting_duration_min").default(30).notNull(),
  meetingLocation: text("meeting_location"),
  createdBy: text("created_by"),
  createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// --- Per-campaign markets (cities) ----------------------------------
// A campaign (offer) can run in several cities at once. A "market" is one
// city/metro: it owns a scrape search, a local phone number, and a filtered
// slice of the campaign's leads / call queue / call log. Leads are tagged to a
// market via campaign_leads.market_id — the lead pool itself stays global and
// shared (a lead's display city still lives in leads.customFields.City).

export const campaignMarkets = pgTable(
  "campaign_markets",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    campaignId: uuid("campaign_id")
      .notNull()
      .references(() => campaigns.id, { onDelete: "cascade" }),
    name: text("name").notNull(), // display label, e.g. "Springfield"
    location: text("location"), // primary scrape location, "Springfield, IL"
    state: text("state"), // "IL" — kept in sync with the market's scrape search
    areaCodes: jsonb("area_codes").$type<string[]>().default([]).notNull(),
    active: boolean("active").default(true).notNull(), // soft-hide a city
    // The market every pre-existing / unscoped lead falls into. Exactly one per
    // campaign, created by the multi-city migration and at campaign launch.
    isDefault: boolean("is_default").default(false).notNull(),
    createdBy: text("created_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("campaign_markets_campaign_idx").on(t.campaignId)],
);

export const campaignLeads = pgTable(
  "campaign_leads",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    campaignId: uuid("campaign_id")
      .notNull()
      .references(() => campaigns.id, { onDelete: "cascade" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => leads.id, { onDelete: "cascade" }),
    // Which city (within this campaign) the lead belongs to. Null = unscoped /
    // "all cities". Set by the harvester from the search's market.
    marketId: uuid("market_id").references(() => campaignMarkets.id, {
      onDelete: "set null",
    }),
    addedAt: timestamp("added_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    uniqueIndex("campaign_leads_uq").on(t.campaignId, t.leadId),
    index("campaign_leads_campaign_idx").on(t.campaignId),
    index("campaign_leads_market_idx").on(t.marketId),
  ],
);

// --- Per-rep script choice -------------------------------------------
// Scripts are a SHARED library per campaign (scripts.campaign_id). Each rep
// picks which one they personally dial with; that pick lives here. The dialer
// falls back to the campaign's primary (campaigns.script_id) when a rep hasn't
// chosen. Cascades on script/campaign delete so a stale pick just reverts to
// the default. One row per (rep, campaign).
export const userCampaignScripts = pgTable(
  "user_campaign_scripts",
  {
    userId: text("user_id").notNull(),
    campaignId: uuid("campaign_id")
      .notNull()
      .references(() => campaigns.id, { onDelete: "cascade" }),
    scriptId: uuid("script_id")
      .notNull()
      .references(() => scripts.id, { onDelete: "cascade" }),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [primaryKey({ columns: [t.userId, t.campaignId] })],
);

// --- Per-campaign phone numbers (local presence) ---------------------
// A Twilio number provisioned for a campaign's geography, so calls show a local
// caller ID (better answer rates). Bought from the campaign builder.

export const campaignNumbers = pgTable(
  "campaign_numbers",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    campaignId: uuid("campaign_id").references(() => campaigns.id, { onDelete: "cascade" }),
    // The city this number is the local caller ID for. Null = a campaign-level
    // number (fallback for any city without its own). Resolved at dial time.
    marketId: uuid("market_id").references(() => campaignMarkets.id, {
      onDelete: "set null",
    }),
    e164: text("e164").notNull(),
    twilioSid: text("twilio_sid"), // IncomingPhoneNumber SID
    areaCode: text("area_code"),
    createdBy: text("created_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("campaign_numbers_campaign_idx").on(t.campaignId),
    index("campaign_numbers_market_idx").on(t.marketId),
  ],
);

// --- Dial sessions ---------------------------------------------------

export const DIAL_SESSION_STATUSES = ["active", "paused", "ended"] as const;
export type DialSessionStatus = (typeof DIAL_SESSION_STATUSES)[number];

export const dialSessions = pgTable("dial_sessions", {
  id: uuid("id").defaultRandom().primaryKey(),
  userId: text("user_id").notNull(),
  campaignId: uuid("campaign_id").references(() => campaigns.id, {
    onDelete: "set null",
  }),
  // The city this session is scoped to. Null = "all cities".
  marketId: uuid("market_id").references(() => campaignMarkets.id, {
    onDelete: "set null",
  }),
  status: text("status").$type<DialSessionStatus>().default("active").notNull(),
  autoDialer: boolean("auto_dialer").default(false).notNull(),
  autoDialerDelaySec: integer("auto_dialer_delay_sec").default(8).notNull(),
  currentLeadId: uuid("current_lead_id").references(() => leads.id, {
    onDelete: "set null",
  }),
  stats: jsonb("stats").$type<Record<string, number>>().default({}),
  startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
  endedAt: timestamp("ended_at", { withTimezone: true }),
});

// --- Call logs (one per dial attempt) --------------------------------

export const callLogs = pgTable(
  "call_logs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    sessionId: uuid("session_id").references(() => dialSessions.id, {
      onDelete: "set null",
    }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => leads.id, { onDelete: "cascade" }),
    // The campaign (offer) this call was made under. Lets a lead shared across
    // campaigns keep each offer's calls in that offer's call log. Null for
    // single-lead calls with no campaign context.
    campaignId: uuid("campaign_id").references(() => campaigns.id, { onDelete: "set null" }),
    // The city (within the campaign) the call was made under, for per-city call
    // logs. Null for single-lead/no-campaign calls.
    marketId: uuid("market_id").references(() => campaignMarkets.id, { onDelete: "set null" }),
    userId: text("user_id").notNull(),
    provider: text("provider").default("stub").notNull(),
    providerCallSid: text("provider_call_sid"),
    direction: text("direction").default("outbound").notNull(),
    status: text("status").default("initiated").notNull(),
    outcome: text("outcome").$type<CallOutcome>(),
    durationSec: integer("duration_sec").default(0),
    notes: text("notes"),
    // Set by the Twilio recording-status callback once the call's audio is
    // recorded (dual-channel). The transcript pipeline reads from here.
    recordingSid: text("recording_sid"),
    recordingDurationSec: integer("recording_duration_sec"),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    endedAt: timestamp("ended_at", { withTimezone: true }),
  },
  (t) => [
    index("call_logs_lead_idx").on(t.leadId),
    index("call_logs_campaign_idx").on(t.campaignId),
    index("call_logs_market_idx").on(t.marketId),
    index("call_logs_user_idx").on(t.userId),
    index("call_logs_call_sid_idx").on(t.providerCallSid),
  ],
);

// --- Call transcripts ------------------------------------------------
// One transcript per recorded call (or manually entered). Segments are
// speaker-attributed so the viewer can render a two-sided conversation and
// downstream coaching/self-improving-script work can reason per speaker.

export const TRANSCRIPT_SOURCES = [
  "twilio_voice_intelligence",
  "deepgram",
  "whisper",
  "manual",
  "browser",
] as const;
export type TranscriptSource = (typeof TRANSCRIPT_SOURCES)[number];

export const TRANSCRIPT_STATUSES = ["pending", "processing", "completed", "failed"] as const;
export type TranscriptStatus = (typeof TRANSCRIPT_STATUSES)[number];

export type TranscriptSpeaker = "agent" | "prospect" | "unknown";

export type TranscriptSegment = {
  speaker: TranscriptSpeaker;
  text: string;
  startMs?: number; // offset from call start
  endMs?: number;
  confidence?: number; // 0..1
};

// Loose bag for AI call notes + coaching output. Kept schemaless (jsonb) so the
// notes/coaching roadmap doesn't need a migration per idea.
export type TranscriptAnalysis = {
  summary?: string; // 1-3 sentence recap of the call
  bullets?: string[]; // key points worth remembering
  nextStep?: string | null; // the concrete follow-up action
  objections?: string[]; // pushback heard, if any
  sentiment?: "positive" | "neutral" | "negative";
  talkRatioAgent?: number; // 0..1 share of words spoken by the agent
  coachingTips?: string[];
  notedAt?: string; // ISO — when AI notes were generated (dedupes timeline note)
  [k: string]: unknown;
};

export const callTranscripts = pgTable(
  "call_transcripts",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    callLogId: uuid("call_log_id").references(() => callLogs.id, { onDelete: "set null" }),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => leads.id, { onDelete: "cascade" }),
    userId: text("user_id"),
    // Parent Twilio CallSid — the join key that lets the recording callback and
    // the in-browser outcome logging meet, regardless of which arrives first.
    callSid: text("call_sid"),
    source: text("source").$type<TranscriptSource>().default("manual").notNull(),
    status: text("status").$type<TranscriptStatus>().default("completed").notNull(),
    recordingSid: text("recording_sid"),
    recordingDurationSec: integer("recording_duration_sec"),
    // Provider-side transcript id (e.g. Twilio Voice Intelligence GT…) for polling.
    providerTranscriptSid: text("provider_transcript_sid"),
    language: text("language").default("en"),
    segments: jsonb("segments").$type<TranscriptSegment[]>().default([]).notNull(),
    text: text("text").default("").notNull(), // denormalized plain text (search/download)
    analysis: jsonb("analysis").$type<TranscriptAnalysis>().default({}).notNull(),
    error: text("error"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("call_transcripts_lead_idx").on(t.leadId),
    index("call_transcripts_call_log_idx").on(t.callLogId),
    index("call_transcripts_call_sid_idx").on(t.callSid),
  ],
);

// --- Bookings (Google Calendar events) -------------------------------

export const bookings = pgTable(
  "bookings",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    leadId: uuid("lead_id")
      .notNull()
      .references(() => leads.id, { onDelete: "cascade" }),
    userId: text("user_id").notNull(),
    title: text("title").notNull(),
    startAt: timestamp("start_at", { withTimezone: true }).notNull(),
    endAt: timestamp("end_at", { withTimezone: true }).notNull(),
    notes: text("notes"),
    googleEventId: text("google_event_id"),
    googleCalendarId: text("google_calendar_id").default("primary"),
    meetingLink: text("meeting_link"),
    status: text("status").default("scheduled").notNull(),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("bookings_user_idx").on(t.userId), index("bookings_start_idx").on(t.startAt)],
);

// --- Per-user Google Calendar OAuth connection -----------------------
// Separate from login (login is email/password). Personal-Gmail tokens
// lapse ~weekly under External/Testing, so we track expiry + allow reconnect.

export const googleConnections = pgTable("google_connections", {
  userId: text("user_id").primaryKey(), // one connection per app user
  googleEmail: text("google_email"),
  accessToken: text("access_token"),
  refreshToken: text("refresh_token"),
  expiryDate: timestamp("expiry_date", { withTimezone: true }),
  scope: text("scope"),
  calendarId: text("calendar_id").default("primary").notNull(),
  connectedAt: timestamp("connected_at", { withTimezone: true }).defaultNow().notNull(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
});

// --- Lead harvesting (saved searches + run log) ----------------------
// A harvestSearch is the "Lead Settings" record: where + how to source new
// leads. The harvester runs it (on-demand button, Vercel cron auto-top-up,
// or pnpm script) and logs each run in harvestRuns.

export const HARVEST_CADENCES = ["on_low", "manual"] as const;
export type HarvestCadence = (typeof HARVEST_CADENCES)[number];

export const HARVEST_TRIGGERS = ["manual", "button", "cron", "script"] as const;
export type HarvestTrigger = (typeof HARVEST_TRIGGERS)[number];

// Resumable pagination state, persisted between (timeout-bounded) runs.
export type HarvestCursor = {
  locationIndex?: number; // which of [location, ...extraLocations] we're on
  pageToken?: string | null; // Google Places next-page token within a location
  done?: boolean; // exhausted all locations
};

export type HarvestStats = {
  found?: number;
  newCount?: number;
  dupes?: number;
  rejected?: number;
  queued?: number;
  approved?: number;
  errors?: string[];
  source?: string; // which discovery source ran ("places" | "osm")
  at?: string; // ISO of the run this summarizes
};

export const harvestSearches = pgTable(
  "harvest_searches",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    label: text("label").notNull(), // "Springfield PM"
    vertical: text("vertical").default("property_management").notNull(),
    keywords: text("keywords"), // free-text term sent to the source ("property management")
    location: text("location").notNull(), // "Springfield, IL"
    state: text("state"), // "IL" — feeds compliance timezone via customFields.City
    radiusMeters: integer("radius_meters").default(40000).notNull(), // Yelp max 40000 (~25mi)
    extraLocations: jsonb("extra_locations").$type<string[]>().default([]).notNull(), // outer metro towns
    providers: jsonb("providers").$type<string[]>().default(["yelp"]).notNull(),
    targetCampaignId: uuid("target_campaign_id").references(() => campaigns.id, {
      onDelete: "set null",
    }),
    // The city (within the target campaign) this search feeds. Leads it ingests
    // are tagged with this market. Null = unscoped / campaign-wide.
    marketId: uuid("market_id").references(() => campaignMarkets.id, {
      onDelete: "set null",
    }),
    // Structured filters (hard pre-filters, applied before any LLM spend).
    requireWebsite: boolean("require_website").default(false).notNull(),
    requirePhone: boolean("require_phone").default(true).notNull(),
    minRating: real("min_rating"),
    minReviews: integer("min_reviews"),
    maxPerRun: integer("max_per_run").default(30).notNull(), // timeout/cost cap per invocation
    // Natural-language rules, passed verbatim into the Haiku classifier.
    customRules: text("custom_rules"),
    // Auto-top-up: cron refills the target campaign when its dialable count
    // drops below this.
    minDialable: integer("min_dialable").default(25).notNull(),
    active: boolean("active").default(true).notNull(), // cron eligibility
    cadence: text("cadence").$type<HarvestCadence>().default("on_low").notNull(),
    cursor: jsonb("cursor").$type<HarvestCursor>().default({}).notNull(),
    lastRunAt: timestamp("last_run_at", { withTimezone: true }),
    lastStats: jsonb("last_stats").$type<HarvestStats>().default({}).notNull(),
    createdBy: text("created_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [index("harvest_searches_active_idx").on(t.active)],
);

export const harvestRuns = pgTable(
  "harvest_runs",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    searchId: uuid("search_id").references(() => harvestSearches.id, { onDelete: "cascade" }),
    trigger: text("trigger").$type<HarvestTrigger>().notNull(),
    found: integer("found").default(0).notNull(), // raw discovery count
    newCount: integer("new_count").default(0).notNull(), // inserted leads
    dupes: integer("dupes").default(0).notNull(), // matched existing (phone or fuzzy)
    rejected: integer("rejected").default(0).notNull(), // auto-archived non-fits
    queued: integer("queued").default(0).notNull(), // reviewState=pending
    approved: integer("approved").default(0).notNull(), // dialable
    errors: jsonb("errors").$type<string[]>().default([]).notNull(),
    startedAt: timestamp("started_at", { withTimezone: true }).defaultNow().notNull(),
    finishedAt: timestamp("finished_at", { withTimezone: true }),
  },
  (t) => [index("harvest_runs_search_idx").on(t.searchId)],
);

// --- Inbound voicemails (the callback inbox) -------------------------
// A prospect calling one of our city numbers back goes to a voicemail greeting
// (app/api/twilio/inbound). The recording lands here — matched to a lead by
// phone when possible (leadId null = unknown caller, still captured so nothing
// is dropped), transcribed by the same engine as call recordings, and surfaced
// in the /inbox so it can be listened to, read, and called back.

export const VOICEMAIL_TRANSCRIPT_STATUSES = [
  "pending",
  "processing",
  "completed",
  "failed",
  "skipped", // no transcription engine configured
] as const;
export type VoicemailTranscriptStatus = (typeof VOICEMAIL_TRANSCRIPT_STATUSES)[number];

export const voicemails = pgTable(
  "voicemails",
  {
    id: uuid("id").defaultRandom().primaryKey(),
    // Matched lead (null = unknown caller — still captured for the inbox).
    leadId: uuid("lead_id").references(() => leads.id, { onDelete: "set null" }),
    // The campaign + city whose local number was called (resolved from `toNumber`).
    campaignId: uuid("campaign_id").references(() => campaigns.id, { onDelete: "set null" }),
    marketId: uuid("market_id").references(() => campaignMarkets.id, { onDelete: "set null" }),
    fromPhone: text("from_phone"), // caller, as Twilio sent it
    fromNormalized: text("from_normalized"), // dedup/match key
    toNumber: text("to_number"), // the city number they called (our caller ID)
    recordingSid: text("recording_sid"),
    recordingUrl: text("recording_url"),
    durationSec: integer("duration_sec").default(0).notNull(),
    transcriptStatus: text("transcript_status")
      .$type<VoicemailTranscriptStatus>()
      .default("pending")
      .notNull(),
    transcriptText: text("transcript_text"),
    // Optional one-line AI gist of the message.
    summary: text("summary"),
    // Inbox triage: mark a voicemail dealt-with (called back / dismissed).
    handled: boolean("handled").default(false).notNull(),
    handledBy: text("handled_by"), // user.id
    handledAt: timestamp("handled_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).defaultNow().notNull(),
  },
  (t) => [
    index("voicemails_created_idx").on(t.createdAt),
    index("voicemails_handled_idx").on(t.handled),
    index("voicemails_lead_idx").on(t.leadId),
  ],
);

// --- Relations -------------------------------------------------------

export const leadsRelations = relations(leads, ({ many }) => ({
  events: many(leadEvents),
  callLogs: many(callLogs),
  bookings: many(bookings),
  campaignLeads: many(campaignLeads),
  transcripts: many(callTranscripts),
  voicemails: many(voicemails),
}));

export const voicemailsRelations = relations(voicemails, ({ one }) => ({
  lead: one(leads, { fields: [voicemails.leadId], references: [leads.id] }),
  campaign: one(campaigns, { fields: [voicemails.campaignId], references: [campaigns.id] }),
  market: one(campaignMarkets, { fields: [voicemails.marketId], references: [campaignMarkets.id] }),
}));

export const callLogsRelations = relations(callLogs, ({ one, many }) => ({
  lead: one(leads, { fields: [callLogs.leadId], references: [leads.id] }),
  transcripts: many(callTranscripts),
}));

export const callTranscriptsRelations = relations(callTranscripts, ({ one }) => ({
  lead: one(leads, { fields: [callTranscripts.leadId], references: [leads.id] }),
  callLog: one(callLogs, { fields: [callTranscripts.callLogId], references: [callLogs.id] }),
}));

export const leadEventsRelations = relations(leadEvents, ({ one }) => ({
  lead: one(leads, { fields: [leadEvents.leadId], references: [leads.id] }),
}));

export const campaignsRelations = relations(campaigns, ({ one, many }) => ({
  script: one(scripts, { fields: [campaigns.scriptId], references: [scripts.id] }),
  campaignLeads: many(campaignLeads),
  markets: many(campaignMarkets),
}));

export const campaignMarketsRelations = relations(campaignMarkets, ({ one, many }) => ({
  campaign: one(campaigns, {
    fields: [campaignMarkets.campaignId],
    references: [campaigns.id],
  }),
  campaignLeads: many(campaignLeads),
  numbers: many(campaignNumbers),
}));

export const campaignLeadsRelations = relations(campaignLeads, ({ one }) => ({
  campaign: one(campaigns, {
    fields: [campaignLeads.campaignId],
    references: [campaigns.id],
  }),
  market: one(campaignMarkets, {
    fields: [campaignLeads.marketId],
    references: [campaignMarkets.id],
  }),
  lead: one(leads, { fields: [campaignLeads.leadId], references: [leads.id] }),
}));

export const bookingsRelations = relations(bookings, ({ one }) => ({
  lead: one(leads, { fields: [bookings.leadId], references: [leads.id] }),
}));

export const harvestSearchesRelations = relations(harvestSearches, ({ one, many }) => ({
  campaign: one(campaigns, {
    fields: [harvestSearches.targetCampaignId],
    references: [campaigns.id],
  }),
  runs: many(harvestRuns),
}));

export const harvestRunsRelations = relations(harvestRuns, ({ one }) => ({
  search: one(harvestSearches, {
    fields: [harvestRuns.searchId],
    references: [harvestSearches.id],
  }),
}));

// --- Better Auth tables (generated) ----------------------------------
export * from "./auth-schema";
